spring:
  application:
    name: agriyo-userservice

server:
  port: 80


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
  instance:
    hostname: localhost